FROM node:8.7.0

COPY ./sources.list /etc/apt/sources.list
RUN apt-get update && apt-get install -y curl wget autoconf automake gcc nasm libtool libpng-dev pkg-config make

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN ls
RUN npm cache verify
RUN npm i --registry http://registry.npm.taobao.org
# use build-config.ssr.json		
RUN rm build-config.json && mv build-config.ssr.json build-config.json
RUN sh build.sh

EXPOSE 4000
# server side render
CMD ["node", "/app/bin/www"]
