version: "3"

services:
  react-starter:
    restart: always
    image: react-starter
    build: .
    container_name: react-starter
    ports:
      - 4000:4000

  react-starter-ssr:
    restart: always
    image: react-starter-ssr
    build:
      context: .
      dockerfile: Dockerfile.ssr
    container_name: react-starter-ssr
    ports:
      - 4001:4000
