version: "3"

services:
  react-stater:
    restart: always
    image: react-stater
    build: .
    container_name: react-stater
    ports:
      - 4000:4000

  react-stater-ssr:
    restart: always
    image: react-stater-ssr
    build:
      context: .
      dockerfile: Dockerfile.ssr
    container_name: react-stater-ssr
    ports:
      - 4001:4000
